### ISSUE TITLE
change class name

### ISSUE THREAD

**Issue by rustamidastan** [kozimov786/pixer-main#1]
https://github.com/kozimov786/pixer-main/blob/0831234955caeecbb6d09333be0395b60cd2bcbb/index.html#L16
Bu yerda `a` tegi `nav` tegining ichida joylashmagan shuning uchun unga class nomini `.nav-logo-link` ko'rinishida e'lon qilish qanchalik to'g'ri?

**Comment by kozimov786** [comment]
> https://github.com/kozimov786/pixer-main/blob/0831234955caeecbb6d09333be0395b60cd2bcbb/index.html#L16
> 
> 
> Bu yerda `a` tegi `nav` tegining ichida joylashmagan shuning uchun unga class nomini `.nav-logo-link` ko'rinishida e'lon qilish qanchalik to'g'ri?

mutlaqo natog'ri oldin ichkarida edi keyin o'zgartirganimda nomini o'zgartirishni unitibman
