### ISSUE TITLE
`margin-right` of logo in `header`

### ISSUE THREAD

**Issue by rustamidastan** [kozimov786/pixer-main#2]
https://github.com/kozimov786/pixer-main/blob/0831234955caeecbb6d09333be0395b60cd2bcbb/css/style.css#L34

I think here using `margin-rigth: auto` is comfortable than giving value to `margin-right`.

**Comment by kozimov786** [comment]
> https://github.com/kozimov786/pixer-main/blob/0831234955caeecbb6d09333be0395b60cd2bcbb/css/style.css#L34
> 
> I think here using `margin-rigth: auto` is comfortable than giving value to `margin-right`.

thank you for good idea
