### ISSUE TITLE
bottom line in `.nav-item`

### ISSUE THREAD

**Issue by rustamidastan** [kozimov786/pixer-main#3]
![image](https://user-images.githubusercontent.com/77572961/115346687-ef497800-a1c9-11eb-95f4-277c7cdd1c86.png)
Bu yerda pastki chiziqni linkni `border-bottom`mi sifatida emas balki, `.nav-item`ning `hover`iga `box-shadow` berib qilgan yaxshiroq.
Masterklassda shunday qilingan)

**Comment by kozimov786** [comment]
> ![image](https://user-images.githubusercontent.com/77572961/115346687-ef497800-a1c9-11eb-95f4-277c7cdd1c86.png)
> Bu yerda pastki chiziqni linkni `border-bottom`mi sifatida emas balki, `.nav-item`ning `hover`iga `box-shadow` berib qilgan yaxshiroq.
> Masterklassda shunday qilingan)

to'g'ri shu hayoldan ko'tarilibdi
